name: haider
favicon: null
layout_spectrum: 0.02872834843583405
typography_spectrum: 0.9598491508513689
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.14362614112906158
  lightness: 0.5577279678545892
  saturation: 0.33067429810762405
  rhythmicContrast: 0.547219555824995
purpose: []
